apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: faker
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: kira-test-simple
  labels:
    kots.io/app-slug: kira-test-simple
    kots.io/backup: velero
  name: example-configmap
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: kira-test-simple
  labels:
    app: example
    component: nginx
    kots.io/app-slug: kira-test-simple
    kots.io/backup: velero
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: kira-test-simple
  labels:
    app: example
    component: nginx
    kots.io/app-slug: kira-test-simple
    kots.io/backup: velero
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      annotations:
        kots.io/app-slug: kira-test-simple
      labels:
        app: example
        component: nginx
        kots.io/app-slug: kira-test-simple
        kots.io/backup: velero
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-configmap
        image: nginx
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
      imagePullSecrets:
      - name: kira-test-simple-registry
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: kira-test-simple
  creationTimestamp: null
  labels:
    kots.io/app-slug: kira-test-simple
    kots.io/backup: velero
  name: kira-test-simple-registry
  namespace: kcboyle
spec:
  encryptedData:
    .dockerconfigjson: AgAcNjQlrgs2SpriChDoVYG4TRzmnspE9BeYuPWM8KyW5RGSWkgEmdi8N9bpkDSmhnkLx9r3Fn2VNm4LhNeZQAZyr7Kdv4yHMhdue6eV5QfQvDtJxaRrlCO1rdTAQTKpCMF/sVLtzkUmlFCBqqUr0kWZuV9CpfrqdLjd9enqwBU2lsVizE8a9STmYiGvEWrX1JB+Nhz79GVuL5LOlXHlxwe6jV+BLwnnS7kNOC8c5EuVCrA148MyOMLioWLCeIhCrh01Eu4fbw/kNgyCIrSRBWbNl70G3C/7MWFKpbFEIn7P4sr306X+nWxpwhzAI6gv/jWXUf3ms0vX6tGOqqjJoLEbFvwMicgNGGFyWz9B2UosPU20EWiHIGpdrK9pTKcHCwFecFSLXH8TR0vJ+qRfwq1+maAM7xfEyov2H0y1PbiXbwEwVvK4x+uoz1usjBsJGg7hfoD3YT6TA7MwkbB4i09rODhyTtb6rutZ3cLZawpFiRBvPFPGWeJReStg1zAg9BiAn63BUi8z5POt4HoHLbXGsVQdh6jmxPdJOce5FeOSJHlrcmxB8gW6kXf5o1/DS1mH6exkrMYWvwr0wrPIREhCXYXHS/nP7Wj0ubLmblMW8kygxyj48X1TbMcuYqLbIRfvysghMvVVDOKm93/ITHQgNx6oB0SSkzKCMS7teTVv77Z+Ib1SKfI6KcL72cwMK4zTb60jd0eFwMkhksbWCH23kPOAzzUqX6TMGGlao7/9eSuRGmHIFe6DWeXaZ5vplXDZ/aTE8GWUWhUWJfE18pzH7+hHxtD2AR+RnKSBwDDGxHufRm8wEKNuDxLUd4fjvVf8Bqm9H7LTOcsxiCmaMVLtg/x66fK66jGemi3NxgIp0ry5eEwce8Aq+co4jNgLrPzgjPdrDj9Gt5op7jTHuBh0637Rw0/KBMzPDLQSR12QpX2w6U3+iHGePQFd0Uj6jc5EDPNfgbt8HBF4J2MRgpOHNq8MlqTtCa5bae+3FU2eiQjQoLLrq3ceienCyQ==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: kira-test-simple-registry
      namespace: kcboyle
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: kira-test-simple
  creationTimestamp: null
  labels:
    kots.io/app-slug: kira-test-simple
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: kcboyle
spec:
  encryptedData:
    .dockerconfigjson: AgBDAmS73f6t8quOD1SXrB0QgM3yf5kkOeX3aJ2StXQw3EwU7lqLYgjdSWUFqhpy4wpJanHS9Ewb5z4AxzBSBh75KYx4czOzYLDRL9qq7UCT9CI2c0Aa2//19JtRGxOwgEIPbEYinxGVHFSmGfzXcV4uEtDFDXrxlOTf/mZsZVmrwsyugSqbBq/yyVulQVAyaykA+jPOyvwWL2bFwoIZ7wHMiYmlwzx5hrIKPHARptHJggXeSF/L5m9EO9iTWe9XaNn0/Xx9BdipBr6xeoWap0bVuTxPWfc1flu2gWwhjoYivjne/NnpL5Z1xk4wKRd/5t74tcPzsmKshRcvDRd73Gl/+5WAZJT/O9M+iHQOj/t206PtoawimbKsBipT7q+dvBZjmXRcHjrmTiMTo1pJVM5YLyXymFnROa6DbCLuz6/betSKu5Ma5YPBJFL8Gn8lOx5qxSfmgFOdxd/fA1XHUQCWJzvroF0+5TxFCVVh/NDpa+P43IgOauudUT2N1bcna3dYsP22OX2n61bx6jb3spIaxZciDmHs6IVWPJwu2ypjYv80SBj6Ugf2p12CrhtyrfTUf83uLvvxB4XkElw791g+Y2SGGTBYP5rA8IiU4G1rjh9UjTkURdFX1RUCJ7uCOXkvnZOxGZRgoeCvrY/JGRvN04meIkUlgVyrWTOmMLUKfVO22j5Qv06lUc9PaPLMLGM/9+eIDq4RA0kHffdPbgvkJi3Z91/LyRL9ltIYpPF/UEcMyMYfy+zZ6MMmZNKgt5PpvDLsvZMTNDetjx752klESYR+mu/Pohj+S8IyhJ5rO45aIg4omXMCCdeRec+jWTzgJdu60il+VAFJ4lsn+Z5ITunbpqWcPl09USjkl2RTECjt+BkGPwAIzZbO8qdtyiwoQuIzIMDs0BhnLrQWZOPOrO9os2/y1ypG7ni1YehyCmcckq3yseJDsLHKIYboRBxZCdXpk5Vhynjcymb7YIs20XeZsN+0D63mYoNWqHCdLYDKvsBOB7dNeZPD9w==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: kotsadm-replicated-registry
      namespace: kcboyle
    type: kubernetes.io/dockerconfigjson
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kots.io/app-slug: kira-test-simple
    kots.io/when: "true"
  labels:
    kots.io/app-slug: kira-test-simple
    kots.io/backup: velero
  name: ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: example-nginx
            port:
              number: 80
        path: /
