apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: faker
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: kira-test-simple
  labels:
    kots.io/app-slug: kira-test-simple
    kots.io/backup: velero
  name: example-configmap
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: kira-test-simple
  labels:
    app: example
    component: nginx
    kots.io/app-slug: kira-test-simple
    kots.io/backup: velero
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: kira-test-simple
  labels:
    app: example
    component: nginx
    kots.io/app-slug: kira-test-simple
    kots.io/backup: velero
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      annotations:
        kots.io/app-slug: kira-test-simple
      labels:
        app: example
        component: nginx
        kots.io/app-slug: kira-test-simple
        kots.io/backup: velero
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-configmap
        image: nginx
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
      imagePullSecrets:
      - name: kira-test-simple-registry
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: kira-test-simple
  creationTimestamp: null
  labels:
    kots.io/app-slug: kira-test-simple
    kots.io/backup: velero
  name: kira-test-simple-registry
  namespace: kcboyle
spec:
  encryptedData:
    .dockerconfigjson: AgAPTbMiglDGKcuL0XIwk34AYRaV+aolF2ZTV7glUbYu14Q+RFdad2Cea7lNRh68Xda7+Zu3TEwMBWAiqHkJpe60gki/I7bW0eQ4ZyCb3QA1c0UKnPdKxv+OOeNxSQDHW0VoYaMXiPsM/3Bh1VTjGblnywb+ITCFIa9H4+ltWVNTK9LkP6aRjwbrIcDn2Tw0qZUduNBoKdll7ZUVpA9X/Qcg66dRoJSXuxTnE2D/XjQGGGY4NrPgXXGX2omme1M1GuDmqyqZ4Gzn81cHvv0LkJKTcJbBiZxEW5/JZmmysWm4YlOK7Zvj2b7YOvGkj7hQ5To1/8sLvGx6MG2pL8e594Q6KoxBVgdw1wFtapSgHvy6iSEjdKPvKuiGQwImaR7MOI4bEw0j3tRr9eJihf+jY+AnmTeBqEEdXYRowFk6UZ3PCF/UQ2Pd75jrQ9aIKVOCKHzuIP5RQnZyo6AU5ANShbpYilC953k9gMmFoXe5YNN9ApYMvTiTxV9VHpto3hmCkksgFozQJ0yOFXKrHtD6eooe4yUacbc5v/TNcy3+4/eBe+iTkz6CiVRKrTrX0v8hAENZViQOU2udmcQYfy3oXVyQg7Gs5GWqHVFvM/qQqGYVCv3w/G5XQLIifUDmWh4JdI4LlM28XSSiRG5awdAAspcdCe6loprER2xnx4z5mCmgYVNzeEWzWv6eGZwJeVNssMvlF/LjL7/QIrO/YBCd69LKz3bhlyw2voQuD1S7kvQXkJOTDjExBTZFi5Q1kVCYDxeAr/ndIVwp3fwBmJl3sKpdKmV+MRjhPzcz/FusBVdrgWVtNkuJGYdztaWkWytNntDSJxMyB6orRQxhZrwBL7iXYj4M5SygVNX9mHOHI8XRhCEMXFItI/jJn41BiW3gu1+8XuYTJ6cJ4g59dFBgGugy/9Zgbef2S4puk9XPSHgDiGkx+c2QtNJ5aR+fJgBNiCF2fJZNIxDsYStzFI3Hz+AFVCKFdO3xmWtktjGk7AX/csglw9B0L3shP6xXgw==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: kira-test-simple-registry
      namespace: kcboyle
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kots.io/app-slug: kira-test-simple
  creationTimestamp: null
  labels:
    kots.io/app-slug: kira-test-simple
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: kcboyle
spec:
  encryptedData:
    .dockerconfigjson: AgBUFy0LvFj0jYtD9/9y7Hg3qTbHFmkNiBW9ixr+Uw8MkwGTJ2l7QfuY1oX1h1iHnNRwwmGchJbD5kUJ/gXv4MRRMEZvVgehYjWxuPlTGsRlBbNEBMoMPlVntBIZqOe1acalxKb6GOtGQxP70mhmL88MkMQEardL86S6k8V+/y5xadrVwA9/Xc2CkS72gVjlQoocE/NJRW0G+RbQ3dldFZbDCXAHZIY22H+Q9B7ae3BG3weWfyJAqCVMpRi3zuBVhzeDEhsDu/WrPIAc2cfXlHDexu7bv69SFkWhRuaHh+JJFYOlTJPE1a+GaQF/jXRgfERfxYjntlJ8uR7b47xfQ0Ii9x6/Cj08W36sXloSf57mpOFCQBpDKv1qaViwVEI/oxvdLNSPyRovuYIZcNh354WnyxRRIGsstT7WeTCuxMDM6eQCSh4M09x/y9WLmFrCeayl3C2TNlq9oH1tMdPiSjJ/Q0K63/UXQEtqSvNALA6n4XgUc/sd+stPQnyTIXmD0wPRAERFTG7/2RhM3fngf8cmJo9yEoUW+A6xddAcZIiQ2G495OcPa4hmCxh2GjaYxZc/niHFdeZOsZYigbbkk+OW/7XtkK7HSqzt8sDyhxNdAAJRZOsUHkEyRMsUwox3LUNn6VQ5nQAcJqftM5TLvMcem2uJYbVUWJv63RFXSoeRnCokOOD0T7+KAR4IwNI59NBfvs6a2O0YaYnKrs6k+Ok9B/ua2ZssHbeCYuxtuYCKa5mBF0A1dl5nPERGGT0greCJyaaR76oN8kusMKnc/hkcgrzdr4d8CYOzGFSCBD2G+XtU2yzJI1ij5CkSfqNouJjWuFMzNqBhlDP/NFcDlqV/CfRYvjK9hcQEgkgvfNu51FSK5CLJRLwfkIEp85eUdMS7vbzwVUrNVBEBZSDiGcuKwwAXYAx6I3+u3e+Q/5sm/QcblUhlRnkEBTS2LuK61NV9ehdgByY6NPGvmf2AM0e5GmbNDH0TiFOj2WwRCgtY5Y185pZPZRBaRYaImA==
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-9999"
      creationTimestamp: null
      name: kotsadm-replicated-registry
      namespace: kcboyle
    type: kubernetes.io/dockerconfigjson
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kots.io/app-slug: kira-test-simple
    kots.io/when: "true"
  labels:
    kots.io/app-slug: kira-test-simple
    kots.io/backup: velero
  name: ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: example-nginx
            port:
              number: 80
        path: /
